name: custom_recorder
description: "A new Flutter plugin project."
version: 0.0.4
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  custom_recorder_platform_interface:
    path: ./custom_recorder_platform_interface
  custom_recorder_android:
    path: ./custom_recorder_android
  custom_recorder_ios_macos:
    path: ./custom_recorder_ios_macos
  custom_recorder_linux:
    path: ./custom_recorder_linux
  custom_recorder_windows:
    path: ./custom_recorder_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        default_package: custom_recorder_android
      ios:
        default_package: custom_recorder_ios_macos
      macos:
        default_package: custom_recorder_ios_macos
      windows:
        default_package: custom_recorder_windows
      linux:
        default_package: custom_recorder_linux
